version: '3.7'
services:
  postgresql:
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - "PGPASSWORD=${POSTGRES_PASS}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASS}"
    ports:
      - "127.0.0.1:54321:5432"
    networks:
      - "api.network"
  ms-go:
    build:
      context: .
      dockerfile: ./build/dev/Dockerfile
    container_name: "ms-go"
    ports:
      - "127.0.0.1:8005:8005"
    volumes:
      - ./:/var/www
    links:
      - postgresql
    networks:
      - "api.network"
networks:
  api.network: